language: scala

dist: precise

scala:
- 2.11.11
- 2.12.3

env:
- SCALAENV=jvm
- SCALAENV=js
- FREESBUILD=docs

matrix:
  exclude:
  - scala: 2.11.11
    env: FREESBUILD=docs

jdk:
- oraclejdk8

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/cache
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.ivy2

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_b98060c2aae7_key -iv $encrypted_b98060c2aae7_iv -in secring.gpg.enc -out secring.gpg -d;
  fi
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.2.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.4.3

script:
- ./scripts/build.sh

after_success:
- if [ "$TRAVIS_SCALA_VERSION" = "2.12.3" -a "$SCALAENV" = "jvm" ]; then
    bash <(curl -s https://codecov.io/bash);
  fi
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess